### ISSUE TITLE
any sample input file for testing

### ISSUE THREAD

**Issue by oberon168** [google/REAPER#13]
I am getting this error message on a test wav file, not sure what format is the program expecting. A working sample wav file would help.

Attempt to load multi channel audioFailed to load waveform

**Comment by gillesdegottex** [comment]
you're loading an audio file with multiple channels, REAPER deals with single channel files only (as far as I know).

Thea README.md reads also:

> Input Signals:
> 
> As written, the input stage expects 16-bit, signed integer samples. Any reasonable sample rate may be used, but rates below 16 kHz will introduce increasingly coarse quantization of the results, and higher rates will incur quadratic increase in computational requirements without gaining much in output accuracy.

**Comment by oberon168** [comment]
yes, saved to mono fixed the problem, the recording program saved in stereo by default. Thank you
