### ISSUE TITLE
EpochTracker's destructor not freeing memory

### ISSUE THREAD

**Issue by kkawabat** [google/REAPER#24]
I am trying to wrap reaper as a c extension for a python program however I noticed that there is a memory leak when calling a modified version of epoch_tracker_main.cc

I am not too familiar with C++ but the destructor for EpochTracker is [empty](https://github.com/google/REAPER/blob/a3926d3c256bcdc500e7b524ebed56c05a5fbc3a/epoch_tracker/epoch_tracker.cc#L38) 

so I've added a call to [CleanUp()](https://github.com/google/REAPER/blob/a3926d3c256bcdc500e7b524ebed56c05a5fbc3a/epoch_tracker/epoch_tracker.cc#L45) method inside the destructor and and the leak seems to disappear. 

```
EpochTracker::~EpochTracker(void) {
   CleanUp();
}
```

I was wondering if this makes sense as I am unfamiliar with c++ conventions

**Comment by xavigonzalvo** [comment]
Memory management in Reaper is far from ideal. I believe your solution is adequate and I wonder why that wasn't already used already from the destructor. The only possible explanation I can think of is that it was giving problems at some point.

I've made the changed you proposed and I'll track that it doesn't produce any problems.

https://github.com/google/REAPER/commit/1d6e9b95e6b08b500fccbc9a043989dbda747276
