### ISSUE TITLE
Segmentation fault (core dumped) when audio file is all zeros 

### ISSUE THREAD

**Issue by kkawabat** [google/REAPER#25]
when the file does not have any signal (all zeros) the number of resid_peaks is 0 which causes an index out of bound error in [EpochTracker::BacktrackAndSaveOutput() line 1029](https://github.com/google/REAPER/blob/a3926d3c256bcdc500e7b524ebed56c05a5fbc3a/epoch_tracker/epoch_tracker.cc#L1028)

**Comment by kkawabat** [comment]
adding the below code before the for loop prevented crash

```
  if (resid_peaks_.size() == 0) {
    fprintf(stderr, "No residule peaks found\n");
    return false;
  }
```

**Comment by xavigonzalvo** [comment]
Added check in [https://github.com/google/REAPER/commit/80eb811151d5272f1f75d1c91fbbfc3217303310](80eb811151d5272f1f75d1c91fbbfc3217303310).

Thanks
